<a href="https://colab.research.google.com/github/manojboyapati/Manoj_Data690/blob/main/Assignment_05/Assignment_05_Part_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import sys
import numpy as np

**Basic Numpy Arrays**

In [15]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [16]:
a = np.array([1, 2, 3, 4])

In [17]:
b = np.array([0, .5, 1, 1.5, 2])

In [18]:
a[0], a[1]

(1, 2)

In [19]:
a[0:]

array([1, 2, 3, 4])

In [20]:
a[1:3]

array([2, 3])

In [21]:
a[1:-1]

array([2, 3])

In [22]:
a[::2]

array([1, 3])

In [23]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [24]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [25]:
b[[0, 2, -1]]

array([0., 1., 2.])

**Array Types**

In [26]:
a

array([1, 2, 3, 4])

In [27]:
a.dtype

dtype('int64')

In [28]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [29]:
b.dtype

dtype('float64')

In [30]:
np.array([1, 2, 3, 4], dtype=np.float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


array([1., 2., 3., 4.])

In [31]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [32]:
c = np.array(['a', 'b', 'c'])

In [33]:
c.dtype

dtype('<U1')

In [34]:
d = np.array([{'a': 1}, sys])

In [35]:
d.dtype

dtype('O')

**Dimensions and shapes**

In [36]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [37]:
A.shape

(2, 3)

In [38]:
A.ndim

2

In [39]:
A.size

6

In [40]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [41]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [42]:
B.shape

(2, 2, 3)

In [43]:
B.ndim

3

In [44]:
B.size

12

In [45]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  import sys


In [46]:
C.dtype

dtype('O')

In [47]:
C.shape

(2,)

In [48]:
C.size

2

In [49]:
type(C[0])

list

**Indexing and Slicing of Matrices**

In [50]:
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [51]:
A[1]

array([4, 5, 6])

In [52]:
A[1][0]

4

In [53]:
A[1, 0]

4

In [54]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [56]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [57]:
A[:2, 2:]

array([[3],
       [6]])

In [58]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
A[1] = np.array([10, 10, 10])

In [60]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [61]:
A[2] = 99

In [62]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

**Summary statistics**

In [63]:
a = np.array([1, 2, 3, 4])

In [64]:
a.sum()

10

In [65]:
a.mean()

2.5

In [66]:
a.std()

1.118033988749895

In [67]:
a.var()


1.25

In [68]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [69]:
A.sum()

45

In [70]:
A.mean()

5.0

In [71]:
A.std()

2.581988897471611

In [72]:
A.sum(axis=0)

array([12, 15, 18])

In [73]:
A.sum(axis=1)

array([ 6, 15, 24])

In [74]:
A.mean(axis=0)

array([4., 5., 6.])

In [75]:
A.mean(axis=1)

array([2., 5., 8.])

In [76]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [77]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

**Broadcasting and Vectorized operations**

In [78]:
a = np.arange(4)

In [79]:
a

array([0, 1, 2, 3])

In [80]:
a + 10

array([10, 11, 12, 13])

In [81]:
a * 10

array([ 0, 10, 20, 30])

In [82]:
a

array([0, 1, 2, 3])

In [83]:
a += 100

In [84]:
a

array([100, 101, 102, 103])

In [85]:
l = [0, 1, 2, 3]

In [86]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [87]:
a = np.arange(4)

In [88]:
a

array([0, 1, 2, 3])

In [89]:
b = np.array([10, 10, 10, 10])

In [90]:
b

array([10, 10, 10, 10])

In [91]:
a + b

array([10, 11, 12, 13])

In [92]:
a * b

array([ 0, 10, 20, 30])

**Boolean arrays**

In [93]:
a = np.arange(4)

In [94]:
a

array([0, 1, 2, 3])

In [95]:
a[0], a[-1]

(0, 3)

In [96]:
a[[0, -1]]

array([0, 3])

In [97]:
a[[True, False, False, True]]

array([0, 3])

In [98]:
a

array([0, 1, 2, 3])

In [99]:
a >= 2

array([False, False,  True,  True])

In [100]:
a[a >= 2]

array([2, 3])

In [101]:
a.mean()

1.5

In [102]:
a[a > a.mean()]

array([2, 3])

In [103]:
a[~(a > a.mean())]

array([0, 1])

In [104]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [105]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [106]:
A = np.random.randint(100, size=(3, 3))

In [107]:
A

array([[85, 36,  1],
       [91, 85,  3],
       [ 0, 83, 97]])

In [108]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([85,  1, 85,  0, 97])

In [109]:
A > 30

array([[ True,  True, False],
       [ True,  True, False],
       [False,  True,  True]])

In [110]:
A[A > 30]

array([85, 36, 91, 85, 83, 97])

**Linear Algebra**

In [111]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [112]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [113]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [114]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [115]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [116]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [117]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

## **Size of objects in Memory**

**Int, floats**

In [118]:
sys.getsizeof(1)

28

In [119]:
sys.getsizeof(10**100)

72

In [120]:
np.dtype(int).itemsize

8

In [121]:
np.dtype(np.int8).itemsize

1

In [122]:
np.dtype(float).itemsize

8

**Lists are even larger**

In [123]:
sys.getsizeof([1])

80

In [124]:
np.array([1]).nbytes

8

**And performance is also important**

In [125]:
l = list(range(100000))

In [126]:
a = np.arange(100000)

In [127]:
%time np.sum(a ** 2)

CPU times: user 0 ns, sys: 849 µs, total: 849 µs
Wall time: 860 µs


333328333350000

In [128]:
%time sum([x ** 2 for x in l])

CPU times: user 43.5 ms, sys: 6.83 ms, total: 50.4 ms
Wall time: 51.6 ms


333328333350000

**Useful Numpy function**

random

In [129]:
np.random.random(size=2)

array([0.05735372, 0.64735016])

In [130]:
np.random.normal(size=2)

array([-1.1161813 ,  1.34764977])

In [131]:
np.random.rand(2, 4)

array([[0.49349607, 0.84170675, 0.23953017, 0.29144424],
       [0.51701796, 0.03889712, 0.75168376, 0.91108044]])

arange

In [132]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [133]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [134]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

reshape

In [135]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [136]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

linspace

In [137]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [138]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [139]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

zeros, ones, empty

In [140]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [141]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [142]:
np.zeros((3, 3), dtype=np.int)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [143]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [144]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [145]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [146]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

identity and eye

In [147]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [148]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [149]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [150]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [151]:
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [152]:
"Hello World"[6]

'W'